export const questions = [
  "A terrible name for a children's hospital",
  "The world's worst superpower",
  "Something you should never say at a job interview",
  "A bad name for a dating app",
  "The worst thing to find in your cereal",
  "A rejected slogan for McDonald's",
  "Something you should never Google",
  "The worst place to fall asleep",
  "A bad name for a funeral home",
  "Something even worse than Mondays",
  "The world's most useless invention",
  "A terrible name for a cat",
  "The worst advice you could give a new parent",
  "Something you should never say on a first date",
  "A rejected name for a superhero",
  "The last thing you want to hear from your pilot",
  "A bad name for a restaurant",
  "The worst thing to put on a pizza",
  "Something that would instantly ruin a birthday party",
  "A rejected name for a law firm",
  "The worst thing to say at a wedding toast",
  "A bad name for a gym",
  "Something aliens would find confusing about humans",
  "The worst possible theme for a children's birthday party",
  "A bad name for a financial advisor",
  "Something you don't want to hear from your dentist",
  "The world's worst ice cream flavor",
  "A terrible idea for a national holiday",
  "Something you should never put on your résumé",
  "The worst thing to text your boss by accident",
];
