import { createServer } from 'node:http';
// @ts-expect-error — generated by adapter-node after `pnpm build`
import { handler } from './build/handler.js';
import { setupWebSocketServer } from './ws-server.js';

const server = createServer(handler);
setupWebSocketServer(server);

const port = Number(process.env.PORT ?? 3000);
server.listen(port, () => {
	console.log(`[server] Listening on http://localhost:${port}`);
});
